version: '3.1'
services:
  app:
    container_name: backend
    image: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=example
  postgresqldb:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=root